const JWT_EXPIRATION_MAX = '3d'
const JWT_EXPIRATION_MIN = '1h'
const JWT_TOKEN_TYPE_LOGIN = 'login'
const JWT_TOKEN_TYPE_RESET_PASSWORD = 'reset password'

module.exports = {
  JWT_EXPIRATION_MAX,
  JWT_EXPIRATION_MIN,
  JWT_TOKEN_TYPE_LOGIN,
  JWT_TOKEN_TYPE_RESET_PASSWORD,
}
