const JWT_EXPIRATION_THREE_DAYS = '3d'
const JWT_EXPIRATION_ONE_HOUR = '1h'
const JWT_TOKEN_TYPE_LOGIN = 'login'
const JWT_TOKEN_TYPE_RESET_PASSWORD = 'reset password'

module.exports = {
  JWT_EXPIRATION_THREE_DAYS,
  JWT_EXPIRATION_ONE_HOUR,
  JWT_TOKEN_TYPE_LOGIN,
  JWT_TOKEN_TYPE_RESET_PASSWORD,
}
